Document: lvr2
Title: Debian lvr2 Manual
Author: <insert document author here>
Abstract: This manual describes what lvr2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lvr2/lvr2.sgml.gz

Format: postscript
Files: /usr/share/doc/lvr2/lvr2.ps.gz

Format: text
Files: /usr/share/doc/lvr2/lvr2.text.gz

Format: HTML
Index: /usr/share/doc/lvr2/html/index.html
Files: /usr/share/doc/lvr2/html/*.html
